### ISSUE TITLE
unable to run biobox cli on mac

### ISSUE THREAD

**Issue by nate-d-olson** [bioboxes/bioboxes-py#36]
Error with writing temp files.  Error message below
```
biobox run short_read_assembler bioboxes/velvet --input reads.fq.gz --output contigs.fa
Traceback (most recent call last):
  File "/Users/nolson/Library/Python/2.7/bin/biobox", line 9, in <module>
    biobox.run()
  File "/Users/nolson/Library/Python/2.7/lib/python/site-packages/biobox_cli/main.py", line 30, in run
    util.select_module("command", opts["<command>"]).run(args)
  File "/Users/nolson/Library/Python/2.7/lib/python/site-packages/biobox_cli/command/run.py", line 26, in run
    ctnr = bbx.run(argv)
  File "/Users/nolson/Library/Python/2.7/lib/python/site-packages/biobox_cli/biobox_helper.py", line 48, in run
    self.after_run(output, output_dir)
  File "/Users/nolson/Library/Python/2.7/lib/python/site-packages/biobox_cli/biobox_type/short_read_assembler.py", line 39, in after_run
    biobox_output = fle.get_biobox_file_contents(host_dst_dir)
  File "/Users/nolson/Library/Python/2.7/lib/python/site-packages/biobox_cli/biobox_file.py", line 9, in get_biobox_file_contents
    with open(os.path.join(dir_, 'biobox.yaml'), 'r') as f:
IOError: [Errno 2] No such file or directory: '/var/folders/nn/7vxcyd6j6h75rp1zxxg71q78001_l1/T/tmprPDTht/biobox.yaml'
```

**Comment by michaelbarton** [comment]
I went over this problem with @nate-d-olson. The error appears to result from the fastq.gz file path not being correct when being given to the biobox Docker container. The error message doesn't convey this output to the user, instead the CLI just crashes out with an obscure error message. The solutions to this are to solve #32 and #31 in the python library, then update the command line interface to correspondingly handle the same cases too.

**Comment by michaelbarton** [comment]
I created the issues bioboxes/command-line-interface#111 and bioboxes/command-line-interface#112, which should also be resolved too.
